name: CI

on:
  workflow_call:
    inputs:
      EXTRA_VARS:
        type: string
        required: false
        description: List of variables as KeyValue separated by ;
        default: ""

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          if [ -n "${{ inputs.EXTRA_VARS }}" ]
          then
            touch .env
            echo "${{ inputs.EXTRA_VARS }}" | sed "s/;/\n/g" | while read line;
            do
              if [ -n "$line" ]; then
                echo "export $line" >> .env
              fi
            done
            source .env
            rm -rf .env
          fi
          source .env
          rm -rf .env
          cat MyTest > TestDir/MyTest
          perl -p -i.bak -E 's:{\{\s*(\S+?)\s*\}}:$ENV{$1} // die "$1 not set":ge' TestDir/MyTest
          cat TestDir/MyTest