name: CI

on:
  workflow_call:
    inputs:
      EXTRA_VARS:
        type: string
        required: false
        description: List of variables as KeyValue separated by ;
        default: ""

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set env
        run: |
          if [ -n "${{ inputs.EXTRA_VARS }}" ]
          then
            echo "${{ inputs.EXTRA_VARS }}" | sed "s/;/\n/g" | while read line; 
            do
              echo "export $line" > .env
            done
          fi
          source .env
          rm -rf .env
          perl -p -i.bak -E 's:{\{\s*(\S+?)\s*\}}:$ENV{$1} // die "$1 not set":ge' MyTest
          cat MyTest