name: Test passing env to workflow

on:
  push:
    branches:
      - main

env:
  WOW: ${{ env.STRING }}
  TEST: '09'
  STRING: 'test-${{ env.TEST }}'

jobs:
  call:
    uses: ./.github/workflows/_callable.yaml
    with:
      EXTRA_VARS: "TEST=09;CLOUD=true;STRING=test;"
